"""initial

Revision ID: 001
Revises: 
Create Date: 2025-03-29 21:01:41.905357

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '001'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chats',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tg_chat_id', sa.BigInteger(), nullable=False),
    sa.Column('inserted_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chats_tg_chat_id'), 'chats', ['tg_chat_id'], unique=True)
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tg_user_id', sa.BigInteger(), nullable=False),
    sa.Column('inserted_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_tg_user_id'), 'users', ['tg_user_id'], unique=True)
    op.create_table('messages',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tg_chat_id', sa.BigInteger(), nullable=False),
    sa.Column('tg_user_id', sa.BigInteger(), nullable=True),
    sa.Column('tg_message_id', sa.BigInteger(), nullable=False),
    sa.Column('md_text', sa.String(), nullable=True),
    sa.Column('sent_at', sa.DateTime(), nullable=False),
    sa.Column('used_auth_key', sa.LargeBinary(), nullable=False),
    sa.Column('used_session_id', sa.LargeBinary(), nullable=False),
    sa.Column('packet', sa.LargeBinary(), nullable=False),
    sa.Column('inserted_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tg_chat_id'], ['chats.tg_chat_id'], ),
    sa.ForeignKeyConstraint(['tg_user_id'], ['users.tg_user_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tg_chat_id', 'tg_message_id', name='uq_tg_chat_id_tg_message_id')
    )
    op.create_index(op.f('ix_messages_tg_chat_id'), 'messages', ['tg_chat_id'], unique=False)
    op.create_index(op.f('ix_messages_tg_message_id'), 'messages', ['tg_message_id'], unique=True)
    op.create_index(op.f('ix_messages_tg_user_id'), 'messages', ['tg_user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_messages_tg_user_id'), table_name='messages')
    op.drop_index(op.f('ix_messages_tg_message_id'), table_name='messages')
    op.drop_index(op.f('ix_messages_tg_chat_id'), table_name='messages')
    op.drop_table('messages')
    op.drop_index(op.f('ix_users_tg_user_id'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_chats_tg_chat_id'), table_name='chats')
    op.drop_table('chats')
    # ### end Alembic commands ###
