"""Added replies

Revision ID: 002
Revises: 001
Create Date: 2025-04-01 03:39:59.289374

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '002'
down_revision: Union[str, None] = '001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('reply_to_tg_message_id', sa.BigInteger(), nullable=True))
    op.drop_index('ix_messages_tg_message_id', table_name='messages')
    op.create_index(op.f('ix_messages_tg_message_id'), 'messages', ['tg_message_id'], unique=False)
    op.create_index(op.f('ix_messages_reply_to_tg_message_id'), 'messages', ['reply_to_tg_message_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_messages_reply_to_tg_message_id'), table_name='messages')
    op.drop_index(op.f('ix_messages_tg_message_id'), table_name='messages')
    op.create_index('ix_messages_tg_message_id', 'messages', ['tg_message_id'], unique=True)
    op.drop_column('messages', 'reply_to_tg_message_id')
    # ### end Alembic commands ###
